# TODO: You can check value of registers by running with -v

- name: "PRELIM | Check for autofs service"
  shell: "systemctl is-enabled autofs"
  args:
      executable: /bin/bash
  register: autofs_service_status
  changed_when: false
  check_mode: false
  when: not debian9cis_skip_for_docker

- name: "PRELIM | Check if prelink package is installed"
  command: dpkg -s prelink
  register: prelink_installed
  changed_when: false
  failed_when: false
  check_mode: false
  tags:
    - skip_ansible_lint

# TODO: apparmor and selinux, maybe switch to package manager ansible_facts

- name: "PRELIM | Check if gdm3 is installed"
  command: dpkg -s gdm3
  register: gdm_installed
  changed_when: false
  failed_when: false
  check_mode: false
  tags:
    - gui

- name: "PRELIM | Populate Service facts"
  service_facts:

- name: "PRELIM | Install netstat"
  apt:
    name:
      - net-tools
    state: present
  when:
    - netstat_install

- name: "PRELIM | Populate open port faces"
  listen_ports_facts:

- name: "PRELIM | Install rsyslog"
  apt:
    name:
      - rsyslog
    state: present
  when:
    - rsyslog
  tags:
    - syslog
    - rule_4.2.3

- name: "PRELIM | Install syslog-ng"
  apt:
    name:
      - syslog-ng
    state: present
  when:
    - syslog
    - ansible_facts.services["syslog-ng.service"] is not defined
  tags:
    - syslog
    - rule_4.2.3

- name: "PRELIM | Re-Populate Service facts"
  service_facts:

# TODO: verify output 5.4.2
- name: "PRELIM | Check that system accounts are non-login #1"
  shell: >
    set -o pipefail &&
    egrep -v "^\+" /etc/passwd | awk -F: '($1!="root" && $1!="sync" &&
    $1!="shutdown" && $1!="halt" && $3<1000 && $7!="/usr/sbin/nologin" &&
    $7!="/bin/false") {print}'
  args:
      executable: /bin/bash
  register: system_accounts_non_login_1
  changed_when: false
  check_mode: false

- name: "PRELIM | Check that system accounts are non-login #2"
  shell: >
    set -o pipefail &&
    for user in `awk -F: '($1!="root" && $3 < 1000) {print $1 }' /etc/passwd`; do
    passwd -S $user | awk -F ' ' '($2!="L") {print $1}'; done
  args:
      executable: /bin/bash
  register: system_accounts_non_login_2
  changed_when: false
  check_mode: false