# TODO: You can check value of registers by running with -v

- name: "PRELIM | Check for autofs service"
  shell: systemctl is-enabled autofs
  args:
      executable: /bin/bash
  register: autofs_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check if prelink package is installed"
  command: dpkg -s prelink
  register: prelink_installed
  changed_when: false
  failed_when: false
  check_mode: false
  tags:
    - skip_ansible_lint